version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/mviewer"
    schedule:
      interval: "daily"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"