{{- $webapp := .Values.mviewer -}}
{{- if $webapp.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mviewer.fullname" . }}-mviewer
  labels:
    {{- include "mviewer.labels" . | nindent 4 }}
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "mviewer.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "mviewer.fullname" . }}-mviewer
  template:
    metadata:
      {{- with $webapp.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mviewer.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "mviewer.fullname" . }}-mviewer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $webapp.podSecurityContext | nindent 8 }}
      {{- with $webapp.nodeSelector }}
      nodeSelector:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      {{- with $webapp.affinity }}
      affinity:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      {{- with $webapp.tolerations }}
      tolerations:
        {{- toYaml . |nindent 8 }}
      {{- end }}
      containers:
      - name: mviewer
        image: "{{ $webapp.image.repository }}:{{ $webapp.image.tag }}"
        imagePullPolicy: {{ $webapp.image.imagePullPolicy }}
        resources:
          {{- toYaml $webapp.resources | nindent 10 }}
        securityContext:
          {{- toYaml $webapp.securityContext | nindent 12 }}
        {{- with $webapp.lifecycle }}
        lifecycle:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
        readinessProbe:
          httpGet:
            path: /
            port: http
        volumeMounts:
        - name: mviewer-conf
          mountPath: /usr/share/nginx/html/apps
          readOnly: true
        {{- if $webapp.extraVolumeMounts }}
          {{- $webapp.extraVolumeMounts | toYaml | nindent 10 }}
        {{- end }}
      volumes:
      - name: mviewer-conf
        persistentVolumeClaim:
          claimName: {{ include "mviewer.fullname" . }}-mviewer-conf
      {{- if $webapp.extraVolumes }}
        {{ $webapp.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
{{- end }}
