apiVersion: v1
kind: Service
metadata:
  name: {{ include "mviewer.fullname" . }}-studio-svc
  labels:
    {{- include "mviewer.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: http
  selector:
    {{- include "mviewer.selectorLabels" . | nindent 4 }}
    app: mviewerstudio
