name: Helm publish on new tag

on:
  push:
    tags:
      - '*'

jobs:
  chart-publish-on-tag:
    runs-on: ubuntu-latest
    steps:
      - name: main Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push Charts to GHCR
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"

      # switch to official https://github.com/helm/chart-releaser-action/issues/107#issuecomment-2133797963
      - name: Run chart-releaser
        uses: acuD1/chart-releaser-action@main
        with:
          skip_upload: true
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Charts to GHCR
        run: |
          for pkg in .cr-release-packages/*; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" oci://ghcr.io/${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY }}
          done