name: Renovate

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 6 * * *' # every day at 6 AM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v42.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}